name: Docker Workflow

# Trigger the workflow on push to any branch
on:
  push:
    branches:
      - main  # Specify branches as needed

jobs:
  run-ord-commands:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (optional)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Pull the Docker image from Docker Hub
      - name: Pull Docker image
        run: docker pull bigsoulja/ord-regtest:latest

      # Step 3: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d --name ord-container bigsoulja/ord-regtest:latest

      # Step 4: Wait for bitcoind and ord server to start
      - name: Wait for services to initialize
        run: |
          # Implement a loop to check if bitcoind is ready
          for i in {1..30}; do
            docker exec ord-container bitcoin-cli -regtest getblockchaininfo && break
            echo "Waiting for bitcoind to be ready..."
            sleep 10
          done
          # Similarly, check if ord server is ready (if applicable)
          # Add any additional checks as necessary

      # Step 5: Create wallet named 'vault'
      - name: Create vault wallet
        run: docker exec ord-container ord -r wallet --name vault create

      # Step 6: Receive address and generate blocks
      - name: Generate blocks to vault address
        run: |
          ADDRESS=$(docker exec ord-container ord -r wallet --name vault receive | jq -r '.addresses[0]')
          docker exec ord-container bitcoin-cli -regtest generatetoaddress 100 "$ADDRESS"

      # Step 7: (Optional) Perform additional tasks
      # Add any other steps you need here

      # Step 8: Clean up Docker container
      - name: Clean up Docker container
        if: always()
        run: |
          docker stop ord-container || true
          docker rm ord-container || true
